---
default_stages: [commit, push]
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
minimum_pre_commit_version: "1.20.0"
repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile
          - black
          - --line-length=88
          - --filter-files
          - --skip-glob
          - "**/migrations/*.py"
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-github-workflows
      - id: check-readthedocs
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.31.0
    hooks:
      - id: yamllint
        args: [-c, .yamllint.yml]
        exclude: feder/letters/logs/cassettes/*
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - --config
          - ./pyproject.toml
          - --exclude
          - 'feder/*/migrations/*.py'
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --config=./setup.cfg
