language: python
python: 2.7

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - DATABASE_URL="mysql://root:@localhost/test_feder"
    - DJANGO_SETTINGS_MODULE="config.settings.tests"
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=coverage


install:
  - pip install -U pip wheel
  - pip install tox
script:
  - tox -e $TOX_ENV
