---
name: Frontend

on:
  push:
    branches:
      - master
      - develop

  pull_request:

jobs:
  regenerate_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Collect statics
        run: docker-compose run web python manage.py collectstatic --noinput
      - name: Build and run frontend
        run: docker-compose up gulp
      - name: Regenerate frontend
        run: make wait_web regenerate_frontend
      - name: Show git status
        run: git status
      - name: Require rebuild content
        run: >
          git diff-index --quiet HEAD -- feder/static/ package*.json || (
            echo "Pending changes in the front-end have been detected.";
            echo "Use 'make regenerate_frontend' to regenerate front-end ";
            echo "and commit changes. Following changes pending:";
            git diff;
            exit 1;
          )
