name: Python package

on: [push]

jobs:
  django:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python: 
          - 3.6
          - 3.7
        django:
          - "==2.2.*"
          - "==3.0.*"
    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - name: Lint check
      run: make lint
    - name: Run side services
      run: make wait_mysql wait_elasticsearch wait_tika
    - name: Build application
      run: docker-compose build web
      env:
        PYTHON_VERSION: ${{ matrix.python }}
        DJANGO_VERSION: ${{ matrix.django }}
        METADEFENDER_API_KEY: ${{ secrets.METADEFENDER_API_KEY }}
    - name: Migration check
      run: make check
    - name: Show MySQL logs
      if: failure()
      run: docker-compose logs db
    - name: Show Elasticsearch logs
      if: failure()
      run: docker-compose logs elasticsearch
    - name: Show Tika logs
      if: failure()
      run: docker-compose logs tika
    - name: Show settings
      run: make settings
    - name: Build test
      run: make test

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build application
      run: make build
      env:
        DJANGO_VERSION: "==2.2.*"
        PYTHON_VERSION: "3.7"
    - name: Run side services
      run: make wait_elasticsearch wait_tika
    - name: Build documentation
      run: make docs
